packages:
  - packages/*
  - "!**/test/**"
catalog:
  globals: ^16.5.0
  eslint: ^9.39.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  prettier: ^3.7.1
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  typescript-eslint: ^8.48.0
  uuid: ^13.0.0
  vitest: ^4.0.14
  vite: ^7.2.4
  zustand: "^5.0.8"
  "@eslint/js": ^9.39.1
  "@vitejs/plugin-react": ^5.1.1
  "@tari-project/tarijs-all": ^0.14.4
  "@tari-project/typescript-bindings": ^1.22.0
  "@tari-project/wallet-connect-signer": ^0.14.4
  "@tari-project/wallet-daemon-signer": ^0.14.4
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@types/vscode": ^1.106.1
  "@types/vscode-webview": ^1.57.5
