export const CALL_NODE_RETURN = "__CALL_NODE_RETURN__";
export const CALL_NODE_RETURN_TUPLE_1 = "__CALL_NODE_RETURN_TUPLE_1__";
export const CALL_NODE_RETURN_TUPLE_2 = "__CALL_NODE_RETURN_TUPLE_2__";
