export const NODE_ENTRY = "__NODE_ENTRY__";
export const NODE_EXIT = "__NODE_EXIT__";
export const COMPONENT_ADDRESS_ENTRY = "__COMPONENT_ADDRESS_ENTRY__";
export const ALLOCATE_COMPONENT_ADDRESS_RESULT = "__ALLOCATE_COMPONENT_ADDRESS_RESULT__";
export const ALLOCATE_RESOURCE_ADDRESS_RESULT = "__ALLOCATE_RESOURCE_ADDRESS_RESULT__";
